services:
  # Symfony backend
  lascar-symfony:
    build: ./Lascar-Symfony
    container_name: lascar-api
    ports:
      - "8000:8000"
    volumes:
      - ./Lascar-Symfony:/var/www
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}

    depends_on:
      - lascar-db

  # React frontend
  lascar-react:
    build: ./Lascar-React
    container_name: lascar-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Lascar-React:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  # MySQL database(db)
  lascar-db:
    image: mysql:8.0
    container_name: lascar-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  lascar-phpmyadmin:
    image: phpmyadmin:latest
    container_name: lascar-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: lascar-db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - lascar-db

volumes:
  db_data:
